version: "3"
services:
    puyo:
        image: gcc:latest
        working_dir: /work
        tty: true
        volumes:
            - ./:/work
        environment:
            - HOME=/work
        command: bash -c "g++ -lncurses puyo.cpp && ./a.out"
